export const EditorTheme = {
  ltr: 'omid-editor-ltr',
  rtl: 'omid-editor-rtl',
  paragraph: 'omid-editor-paragraph',
  quote: 'omid-editor-quote',
  heading: {
    h1: 'omid-editor-h1',
    h2: 'omid-editor-h2',
    h3: 'omid-editor-h3',
    h4: 'omid-editor-h4',
    h5: 'omid-editor-h5',
    h6: 'omid-editor-h6',
  },
  list: {
    nested: {
      listitem: 'omid-editor-nested-listitem',
    },
    ol: 'omid-editor-list-ol',
    ul: 'omid-editor-list-ul',
    listitem: 'omid-editor-listitem',
    listitemChecked: 'omid-editor-listitem-checked',
    listitemUnchecked: 'omid-editor-listitem-unchecked',
    checklist: 'omid-editor-checklist',
  },
  link: 'omid-editor-link',
  code: 'omid-editor-code',
  codeHighlight: {},
  hr: 'omid-editor-hr',
  hrSelected: 'omid-editor-hr-selected',
  image: 'omid-editor-image',
  mention: 'omid-editor-mention',
  video: 'omid-editor-video',
  file: 'omid-editor-file',
  table: 'omid-editor-table',
  tableCell: 'omid-editor-table-cell',
  tableCellHeader: 'omid-editor-table-cell-header',
  tableRow: 'omid-editor-table-row',
  tableSelection: 'omid-editor-table-selection',
  text: {
    bold: 'omid-editor-text-bold',
    italic: 'omid-editor-text-italic',
    underline: 'omid-editor-text-underline',
    strikethrough: 'omid-editor-text-strikethrough',
    underlineStrikethrough: 'omid-editor-text-underlineStrikethrough',
    code: 'omid-editor-text-code',
  },
}
